In [4]:
gary_age = roger_age = tom_age = 24
print("Gry's age = ", gary_age)
print("Roger's age = ", roger_age)
print("Tom's age = ", tom_age) 

Gry's age =  24
Roger's age =  24
Tom's age =  24


In [ ]:
roger_age, roger_income, roger_experience = 7, 1000, 2
print("Roger's age = ", roger_age)
print("Roger's income = ", roger_income)
print("Roger's experience = ", roger_experience)

Roger's age =  7
Roger's income =  1000
Roger's experience =  2


In [7]:
name = "Charles"
print(name)
type(name)

Charles


str

In [10]:
isStudent = True
has_paid_fees = False
print(isStudent)
print(has_paid_fees)
type(isStudent)
type(has_paid_fees)

True
False


bool

In [12]:
myVar = None
print(myVar)
type(myVar)

None


NoneType

In [1]:
student_data = {
    "name": "John",
    "age": 20,
    "is_student": True,
    "courses": ["Math", "Science", "History"],
    "grades": {
        "Math": 90,
        "Science": 85,
        "History": 88
    }
}
print(student_data)

{'name': 'John', 'age': 20, 'is_student': True, 'courses': ['Math', 'Science', 'History'], 'grades': {'Math': 90, 'Science': 85, 'History': 88}}


In [2]:
my_set = {10, 20, 20, 30}
print(my_set)

{10, 20, 30}


Operators

In [1]:
y = 21
print(y//7)

3


In [6]:
a = True
b = False
print(a and b)

False


Bitwise Operator
&: bitwise AND
|: bitwise OR

In [ ]:
x = 2  
y = 5 
print(x & y)
print(x | y)

0
7


Arithmetic Operators 

In [9]:
# adding two numbers
income = 10000
incentives = 1000
total_income = income + incentives
print(total_income)

11000


In [12]:
# adding one float one integer values
income = 10000 
incentives = 12550.50
total_income = income + incentives
total_income


22550.5

Relational Operators

In [11]:
ketty_age = 28
kenny_age = 25
ketty_age == kenny_age 

False

Logical Operators

In [ ]:
is_student = True
in_college = True
in_school = False
is_student and in_college

True

In [18]:
is_student or in_school

True

In [19]:
not(is_student)

False

Bitwise Operators

In [20]:
number = 10
(number % 2 == 0) & (number % 3 == 0)

False

In [21]:
(number % 2 == 0) | (number % 3 == 0)

True

Flow Control

The If Statement

In [22]:
#Check  if a number is greater than zero
num = 8
if(num > 0):
    print(num, "is greater than zero")
print("This is always printed")

8 is greater than zero
This is always printed


In [23]:
#Check  if a number is greater than zero
num = -1
if(num > 0):
    print(num, "is greater than zero")
print("This is always printed")


This is always printed


The If-Else Statement

In [24]:
num = -1
if(num > 0):
    print(num, "is greater than zero")
else:
    print(num, "is less than or equal to zero")

-1 is less than or equal to zero


The If Elif Else Statement

In [33]:
#display bus fares as per age entered by user
age = int(input("Enter age: "))
if(0 <= age <= 3):
    print("No fares for age group 0-3")
elif(3 <= age <= 10):
    print("Bus fare is 20")
elif(10 <= age <= 20):
    print("Bus fare is 25")
else:
    print("Bus fare is 30")

Bus fare is 30


Nested If Else Statement

In [43]:
#find the largest number among the three numbers using nested if-else
num1 = 10
num2 = 34
num3 = 5
if(num1 > num2): 
    print(num1, "is greater")
else:
    if(num3 > num2):
        print(num3, "is greater")
    else:
        print(num2, "is greater")



34 is greater


In [47]:
#Nested if-else to find the greatest 
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))
if a >= b:
    if a >= c:
        greatest = a
    else:
        greatest = c
else:
        if b >= c:
            greatest = b
        else:
             greatest = c
        
print("The greatest number is", greatest)

The greatest number is 7


LOOPS

While Loop

In [48]:
num = 10
addition = 0
i = 1
while(i <= num):
    addition = addition + i
    i = i + 1
print("Addition is: ", addition)

Addition is:  55


For Loop

In [49]:
number = range(1, 11)
addition = 0
for i in number:
    addition = addition + i

print("Addition is: ", addition)

Addition is:  55


Type Casting - 
Explicit Type Casting,
Implicit Type Casting

Breaking Loops & Nested Loops: 
break - exits the loop with its block of code,
continue - skips the loop block of code

In [3]:
text = "knowledgehut"
for letter in text:
    if letter == 'h':
        break
    print(letter)
print("The for loop stopped executing")

k
n
o
w
l
e
d
g
e
The for loop stopped executing


In [3]:
text = "knowledgehut"
for letter in text:
    if letter == 'h':
        print("This block of code has been skipped")
        continue
    print(letter)

k
n
o
w
l
e
d
g
e
This block of code has been skipped
u
t


In [11]:
levels = int(input("Enter number of levels: "))
for level in range(1, levels + 1):
    for num in range(level):
        print(level, end=" ")
    print("\n")

1 

2 2 

3 3 3 

4 4 4 4 

5 5 5 5 5 



Functions: Built-In Functions, User-defined Functions, Lambda Functions

In [ ]:
#Built-in Functions  
#The input() function in Python 
name = (input("Enter your name:"))
#The print() function in Python
print("Hii",name)

Hii Juel


In [15]:
#User-defined Functions
#Syntax - 
#def function_name(parameters):
#     function_body
# function_name
def great(name):
    print("Hello", name)
great("John")

Hello John


In [16]:
#lambda function
# Syntax - 
# lambda arguments : expression
#Example - 
square = lambda x : x * x
print("Square of 5 is: ", square(5))

Square of 5 is:  25


In [ ]:
#Addition of two numbers using function
def myFunction(a, b):
    return a + b
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
print("Sum of", a, "and", b, "is: ", myFunction(a, b))


Sum of 7 and 9 is:  16


In [2]:
#Create a function that return both area and circumference of a circle
def circle(radius):
    area = 3.14 * radius * radius
    circumference = 2 * 3.14 * radius
    return area, circumference
x = int(input("Enter the radius of the circle: "))
print("The area and circumference of the circle having radius ", x, "is", circle(x))

The area and circumference of the circle having radius  7 is (153.86, 43.96)


In [14]:
#Default parameter for a function
def greet(name, msg = "Good morning!"):
    print("Hello", name + ",", msg)
name = input("Enter your name: ")
greet(name)

Hello Juel, Good morning!


In [ ]:
#Write a function that takes variable number of arguments
#return their sum
def sum_all(*args):
    print(args)
    # return sum(args)
    sum = 0
    # for i in args:
    #     sum = sum + i
    # return sum
    while args:
        sum = sum + args[0]
        args = args[1:]
    return sum
print(sum_all(1, 2, 3, 4, 5))

(1, 2, 3, 4, 5)
15


In [ ]:
#Create a function that accept any number of keyword arguments and print them in the form of key=value
# def print_key_value(**kwargs):
#     for key, value in kwargs.items():
#         print(f"{key} = {value}")
#     return type(kwargs)
# print_key_value(name="John", age=25, city="New York")

def print_key_value(**kwargs):
    for key, value in kwargs.items():
        print(f"{key} = {value}")
    return type(kwargs)
dict = {
    "name": "John",
    "age": 25,
    "city": "New York"
}
print_key_value(**dict)



name = John
age = 25
city = New York


dict

In [ ]:
#Factorial of a number 
# n = int(input("Enter a number: "))
# num = n
# for i in range(1,n):
#    n = n * i
# print("Factorial of", num, "is", n)

# def fact(n):
#     if n == 0 or n == 1:
#         return 1
#     else:
#         return n * fact(n - 1)
# num = int(input("Enter a number: "))
# print("Factorial of", num, "is", fact(num))

Factorial of 6 is 720


In [ ]:
#In-buit functions in Python
#abs() - returns the absolute value of a number
#all() - returns True if all elements of the iterable are true
#any() - returns True if any element of the iterable is true
#ascii() - returns a string containing a printable representation of an object
#bin() - returns the binary representation of a number
#bool() - returns the boolean value of an object
#bytearray() - returns a bytearray object
#bytes() - returns a bytes object
#callable() - returns True if the object appears callable
#chr() - returns a string representing a character
#classmethod() - returns a class method for the given function
#compile() - compiles the source into a code or AST object
#complex() - returns a complex number
#print() - prints the given object to the console
#delattr() - deletes the named attribute from the given object
#dict() - creates a dictionary
#dir() - returns a list of the attributes and methods of an object
#divmod() - returns a tuple of the quotient and remainder of dividing two numbers
#enumerate() - returns an enumerate object
#eval() - parses the expression and executes it
#exec() - executes the given code
#filter() - constructs an iterator from elements of an iterable for which a function returns true
#float() - returns a floating point number
#input() - reads a line from input
#int() - returns an integer object
#isinstance() - returns True if the object is an instance of the class
#issubclass() - returns True if the class is a subclass of the class
#iter() - returns an iterator object
#len() - returns the length of an object
#list() - creates a list
#locals() - returns a dictionary of the current local symbol table
#map() - applies a function to all the items in an iterable
#max() - returns the largest item in an iterable
#memoryview() - returns a memory view object
#min() - returns the smallest item in an iterable
#next() - retrieves the next item from the iterator
#object() - returns a new featureless object
#oct() - returns the octal representation of a number
#open() - opens a file and returns a file object
#ord() - returns an integer representing the Unicode code of a character
#pow() - returns the value of x to the power of y
#print() - prints the given object to the console
#property() - returns a property attribute
#range() - returns a sequence of numbers
#repr() - returns a string containing a printable representation of an object
#reversed() - returns a reversed iterator
#round() - rounds a number to a given precision
#set() - creates a set
#setattr() - sets the named attribute on the given object
#slice() - returns a slice object
#sorted() - returns a sorted list of the specified iterable object
#staticmethod() - returns a static method for the given function
#str() - returns a string object
#sum() - returns the sum of a start value (default 0) plus an iterable of numbers
#super() - returns a proxy object that delegates method calls to a parent or sibling class
#tuple() - creates a tuple
#type() - returns the type of an object
#vars() - returns the __dict__ attribute of an object
#zip() - returns an iterator of tuples
#map() - applies a function to all the items in an iterable
#filter() - constructs an iterator from elements of an iterable for which a function returns true
#reduce() - applies a rolling computation to sequential pairs of values in a list


In [ ]:
# username = "John"
# def function():
#     username = "Sumit"
#     print(username)
# function()
# print(username)
# x = 99
# def func(y):
#     z = x+y
#     return z

# result = func(1)
# print(result)


100


Class

In [ ]:
# class Bike(object):
#     def __init__(self, name, color):
#         self.name = name
#         self.color = color

#     def display(self):
#         print("Bike Name: ", self.name)
#         print("Bike Color: ", self.color)
    
# Bike("Yamaha", "Red").display()

#Add a method  to the Bike class that display the fullname of the Car(brand and model)
class Bike:
    def __init__(self, brand, model):
        self.brand = brand
        self.model = model

    def display(self):
        print("Bike Brand: ", self.brand)
        print("Bike Model: ", self.model)
    def car(brand, model):
        print("Car Brand: ",brand)
        print("Car Model: ",model)
mybike = Bike("honda", "cbz")
print(mybike.brand)
print(mybike.model)
mybike.display()
mycar = Bike.car("Toyota", "fortuner")


honda
cbz
Bike Brand:  honda
Bike Model:  cbz
Car Brand:  Toyota
Car Model:  fortuner


In [33]:
#Create a ElectricBike class that inherits from the Bike class and has an additional attribute
# for battery capacity
class ElectricBike(Bike): 
    def __init__(self, brand, model, battery_capacity):
        super().__init__(brand, model)
        self.battery_capacity = battery_capacity

    def display(self):
        super().display()
        print("Battery Capacity: ", self.battery_capacity)
myebike =  ElectricBike("Ola", "S1 Pro", "4 kWh")
myebike.display()

Bike Brand:  Ola
Bike Model:  S1 Pro
Battery Capacity:  4 kWh


In [10]:
class Car:
    def __init__(self, brand, model):
        self.brand = brand
        self.model = model
    def display(self):
        print("Car Brand: ", self.brand)
        print("Car Model: ", self.model)

mycar = Car("Toyota", "Corolla")
mycar.display()

Car Brand:  Toyota
Car Model:  Corolla


OOPS

Class

In [3]:
#Create an object car and print its brand
class Car:
    def __init__(self, brand, model):
        self.brand = brand
        self.model = model
    def display(self):
        print("Car Brand: ", self.brand)
        print("Car Model: ", self.model)

mycar = Car("Mercedes-Benz", "C-Class")
mycar.display()

Car Brand:  Mercedes-Benz
Car Model:  C-Class


Getter and Setter

In [ ]:
#Getter and Setter functions in Python
class Car:
    def __init__(self, brand, model):
        self.brand = brand
        self.__model = model

    def get_model(self):
        return self.__model

    def set_model(self, new_value):
        self.__model = new_value

mycar = Car("Ford", "Mustang")
print(mycar.get_model())
mycar.set_model("Endeavour")
print(mycar.get_model())


Mustang
Endeavour


Inheritance 

In [3]:
#Create a class vehicle and create a method to start the engine
class Vehicle:
    def start_engine(self):
        pass

class Car(Vehicle):
    count = 0
    def __init__(self, brand, model, year):
        self.brand = brand
        self.__model = model
        self.year = year
        self.is_running = False
        Car.count += 1

    def get_model(self):
        return self.__model
    def set_model(self, new_value):
        self.__model = new_value
    def start_engine(self):
        self.is_running = True
        print(f"{self.brand} {self.__model} engine started.")
    @classmethod
    def get_count(cls):
        return cls.count

mycar = Car("Tesla", "Model S", 2022)
mycar = Car("Ford", "Mustang", 2021)
mycar.start_engine()

class ElectricCar(Car):
    def start_engine(self):
        print(f"{self.brand} {self.get_model()} electric engine started.")
my_electric_car = ElectricCar("Tesla", "Model 3", 2022)
my_electric_car.start_engine()   

count = Car.get_count()
print(f"Number of objects created: {count}")

Ford Mustang engine started.
Tesla Model 3 electric engine started.
Number of objects created: 3


Decorators

In [2]:
#Decorators
# def decorator_name(func):
#     def wrapper(*args, **kwargs):
#         result = func(*args, **kwargs)
#         return result
#     return wrapper
# @decorator_name
# def function_to_decorate():
#     print("This function is decorated.")

def my_decorator(func):
    def wrapper():
        print("Before the function runs")
        func()
        print("After the function runs")
    return wrapper

@my_decorator
def say_hello():
    print("Hello, world!")

say_hello()

Before the function runs
Hello, world!
After the function runs


In [11]:
def area(function):
    def wrapper(*args, **kwargs):
        result = function(*args, **kwargs)
        print(f"Area of rectangle is: {result}")
        return result
    return wrapper

@area
def rectangle(length, breadth):
    return length * breadth
(rectangle(10, 20))
def area(function):
    def wrapper(*args, **kwargs):
        result = function(*args, **kwargs)
        print(f"Area of square is: {result}")
        return result
    return wrapper
@area
def square(side):
    return side * side
(square(5))

def area(function):
    def wrapper(*args, **kwargs):
        result = function(*args, **kwargs)
        print(f"Addition of two numbers is: {result}")
        return result
    return wrapper
@area
def add(num1, num2):
    return num1 + num2
(add(10, 20))

Area of rectangle is: 200
Area of square is: 25
Addition of two numbers is: 30


30

Numpy

In [ ]:
import numpy as np
print(np.__version__)

2.2.6


In [20]:
#Creating Arrays
import numpy as np

#Create a 1D array
# arr = np.array([1, 2, 3])
# print(arr)

#Create a 2D array
# arr = np.array([(1, 2, 3), (4, 5, 6)])
# print(arr)

#1D array of length3;all values set to 0
# arr = np.zeros(3)
# print(arr)

#3*4 array with all values set to 1
# arr = np.ones((3, 4))
# print(arr)

#5*5 array of 0 with 1 on diagonal(identity matrix)
# arr = np.eye(5)
# print(arr)

#LINSPACE
# arr = np.linspace(0, 100, 6)
# print(arr)

#ARANGE
# arr = np.arange(0, 10, 3)
# print(arr)

#2*3 array with all values set to 8
# arr = np.full((2, 3), 8)
# print(arr)

#4*5 array of random floats between 0 and 1
# arr = np.random.rand(4, 5)
# print(arr)
# arr = np.random.rand(6, 7) * 100
# print(arr)

# 2*3 array with random integers between 0 and 4
# arr = np.random.randint(5, size=(2, 3))
# print(arr)
np.random.seed(3)
arr = np.random.randint(0, 10, 5)
print(arr)
# list = [1, 2, 3, 4, 5]
# print(list * 2)
# arr = np.array(list) * 2
# print(arr)


[8 9 3 8 8]


In [ ]:
#Inspecting Properties
import numpy as np

#Convert arr elements to type dtype
# arr = np.array([1, 2, 3])
# dtype = np.float64
# arr.astype(dtype)

# Convert arr to a Python list
# arr.tolist()

#View documentation for np.eye
# np.info(np.eye)

#Returns number of elements in arr
# arr.size

#Returns dimensions of arr(rows, columns)
# arr.shape

#Returns type of elements in arr
# arr.dtype


# arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
# arr.shape
# arr.size
# arr.dtype
# arr.itemsize 
# arr.ndim

#Type Conversion
# arr = np.array([1.5, 2.5, 3, 4.5], dtype=np.int64)
# arr.dtype
# arr = np.array([1, 2, 3, 4])
# arr.astype(float)

#Matrix addition
# arr1 = np.array([[1, 2, 3],
#                  [4, 5, 6]])
# arr2 = np.array([[7, 8, 9]])
# arr3 = arr1 + arr2
# print(arr3)


[[ 8 10 12]
 [11 13 15]]


In [ ]:
#Copying, Sorting, & Reshaping

# Copies arr to new memory
# np.copy(arr)

#Create view of arr elements with type dtype
# arr.view(float)

#Sorts arr
# arr = np.array([3, 1, 2])
# arr.sort()
# print(arr)

#Sorts specific axis of arr
# arr = np.array([[3, 1, 2], [6, 5, 4]])
# arr.sort(axis=0)
# print(arr)

#Flattens 2D array two_d_arr to 1d
# two_d_arr = np.array([[1, 2, 3], [4, 5, 6]])
# two_d_arr.flatten()

#Transposes arr(rows become columns and vice versa)
# arr = np.array([[3, 1, 2], [4, 5, 6]])
# arr.T

#Reshapes arr to 3 rows, 2 columns without changing data
# arr = np.array([1, 2, 3, 4, 5, 6])
# arr.reshape(3, 2)

#Changes arr shape to 3 rows, 2 columns and fills with 2
# arr.resize(5, 6)
# print(arr)

[[1 2 3 4 5 6]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [ ]:
# Adding & Removing Elements
# arr = np.array([[1, 2, 3], [4, 5, 6]])
# np.append(arr, [7, 8, 9])
# np.insert(arr, 2, [7, 8])
# np.delete(arr, 1, axis=0)
# np.delete(arr, 1, axis=1)

array([[1, 3],
       [4, 6]])

In [ ]:
# Combining & Splitting  
# arr1 = np.array([[1, 2, 3], [4, 5, 6]])
# arr2 = np.array([[7, 8, 9], [10, 11, 12]])
# np.concatenate((arr1, arr2), axis=0)
# arr = np.array([5, 7, 9])
# np.split(arr, 3)
# arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# np.hsplit(arr, 5)

[array([[1],
        [6]]),
 array([[2],
        [7]]),
 array([[3],
        [8]]),
 array([[4],
        [9]]),
 array([[ 5],
        [10]])]

In [ ]:
# Indexing & Slicing
# arr = np.array([1, 2, 3, 4, 5, 6])
# arr[5]

# arr = np.array([[1, 2, 3], [4, 5, 6]])
# arr[2, 5]
# arr[1] = [4]
# print(arr)
# arr[1, 1] = 10
# print(arr)


['a', 'b', 'c']

Pandas

In [ ]:
# import pandas as pd
# print(pd.__version__)

# s1 = pd.Series([1, 2, 3, 4, 5])
# s1
# import numpy as np
# arr = np.array((1, 2, 3, 4, 5))
# s2 = pd.Series(arr)
# s2

# age_series_index = pd.Series(
#     np.array([20, 37, 45, 25, 76, 55]), 
#     index = np.arange(0, 12, 2)
# )
# age_series_index

# std_mark_series = pd.Series(
#     np.array([90, 80, 70, 60, 50]), 
#     index = ['A', 'B', 'C', 'D', 'E']
# )
# std_mark_series

# expense_dict = {'rent':2500, 'grocery':3000, 
#                 'travelling':2000, 'insurance':5000}
# expense_series = pd.Series(expense_dict)
# expense_series

# classes_dict = {
#     "A": ["Maths", "Science", "English"],
#     "B": ["Maths", "Physics"],
#     "C": "Chemistry"
# }
# classes_series = pd.Series(classes_dict)
# # classes_series.index
# classes_series.values

# std_data = np.array(['Ram', 'Sita', 'Laxmi', 
#                      'Krishna', 'Madhab', 'Arjun'])
# std_data_series = pd.Series(std_data)
# print(std_data_series[:5])
# print(std_data_series[-5:])

# classes_dict = {
#     "A": ["Maths", "Science", "English"],
#     "B": ["Maths", "Physics"],
#     "C": "Chemistry"
# }
# classes_series = pd.Series(classes_dict)
# print(classes_series)
# print("\n", classes_series[['A', 'B']])

# student_series = pd.Series(
#     np.array([457, 456, 540, 348, 502, 480]),
#     index = ['Ram', 'Sita', 'Laxmi', 'Krishna', 'Madhab', 'Arjun']
# )
# student_series[student_series > 350]

# new_series1 = pd.Series([1, 2, 4, 5])
# new_series2 = pd.Series([10, 20, 30, 40])

# new_series1 + new_series2
# new_series1 - new_series2 
# new_series1 * new_series2
# new_series1 / new_series2
# new_series1 % new_series2

# sales_series = pd.Series(np.array([200, 590, 367, 678, 455]))
# sales_series*2

# student_scores = pd.Series(
#     [88, 92, 75, 91, 85],
#     index=['Alice', 'Bob', 'Charlie', 'David', 'Eva']
# )
# student_ranks = student_scores.rank(ascending=False)
# print("\nStudent Ranks:\n", student_ranks)

# sales_data = pd.Series(
#     [250, np.nan, 175, 300, np.nan, 220],
#     index=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']
# )
# sorted_sales = sales_data.sort_values(na_position='last')
# print("\nSorted Sales Data (NaNs last):\n", sorted_sales)

# sorted_sales = sales_data.sort_values(ascending=False, na_position='first')
# print("\nSorted Sales Data (NaNs last):\n", sorted_sales) 

# sales_data = pd.Series(
#     [250, np.nan, 175, 300, np.nan, 220],
#     index=[7,4,3,2,8,9]
# )
# sorted_sales = sales_data.sort_index(ascending=True)
# print("\nSorted Sales Data (NaNs last):\n", sorted_sales) 



Sorted Sales Data (NaNs last):
 2    300.0
3    175.0
4      NaN
7    250.0
8      NaN
9    220.0
dtype: float64


In [ ]:
# import pandas as pd
# import numpy as np

# # sales_data = pd.Series(
# #     [250, np.nan, 175, 300, np.nan, 220],
# #     index=[7, 4, 3, 2, 8, 9]
# # )
# # sales_data.isnull()
# # sales_data.notnull()

# # week1_sales=np.linspace(start=0, stop=300, num=5)
# # week2_sales=np.linspace(start=0, stop=400, num=5)

# # week1_sales_series = pd.Series(data=week1_sales)
# # week2_sales_series = pd.Series(data=week2_sales)
# # print("Week 1 Sales Series:\n", week1_sales_series)
# # print("Week 2 Sales Series:\n", week2_sales_series)

# # pd.concat([week1_sales_series, week2_sales_series])
# # week1_sales_series.append(week2_sales_series)

# #DataFrames

# # machine_learning=['Python', 'NumPy', 'Pandas', 'Matplotlib', 'ML Algorithm', 'Statistics']
# # df=pd.DataFrame(machine_learning, columns=['Machine Learning'])
# # df

# #create a dataframe from a list of list
# # courses_list=[['ML foundation', 8000], ['IOT', 5000], ['Web development', 6500], ['O level', 4500]]
# # df = pd.DataFrame(courses_list, columns=['Couse', 'Fee'])
# # df

# #create dataframe from a dictionary
# # data = {
# #     'Name': ['Alice', 'Bob', 'Charlie'],
# #     'Age': [24, 27, 22],
# #     'City': ['New York', 'Los Angeles', 'Chicago']
# # }
# # df = pd.DataFrame(data)
# # df

# #create dataframe with index from a dictionary
# # data = {
# #     'Name': ['Alice', 'Bob', 'Charlie'],
# #     'Age': [24, 27, 22],
# #     'City': ['New York', 'Los Angeles', 'Chicago']
# # }
# # df = pd.DataFrame(data, index=['A1', 'A2', 'A3'])
# # df

# #create a dataframe from a list of dictionaries

# #list of dictionaries with sales data
# # sales_data = [
# #     {'Data': '2025-06-01', 'Product': 'Laptop', 'Units_Sold': 5, 'Revenue': 50000},
# #     {'Data': '2025-06-01', 'Product': 'Mouse', 'Units_Sold': 25, 'Revenue': 2500},
# #     {'Data': '2025-06-02', 'Product': 'Keyboard', 'Units_Sold': 15, 'Revenue': 7500},
# #     {'Data': '2025-06-02', 'Product': 'Monitor', 'Units_Sold': 7, 'Revenue': 21000}
# # ]
# # df=pd.DataFrame(sales_data)
# # df

# df = pd.read_excel('mywork.xlsx', sheet_name='Sheet1')
# df

# # df = pd.read_csv('mywork.csv')
# # df

# # df = pd.read_json('iris.json')
# # df.head() 
# # df.tail()
# # df.describe()

# df = pd.read_csv('Obesity Classification.csv')
# df 

# df.index=["First", 'Second', "Third"]
# df.columns=["Name", "Age", "City", "Pincode"]

Name  Age         City  Pincode
0     Tony   25     New York   826761
1     Thor   25     New York   281771
2   Gaurav   25       Mumbai   292872
3    Bhola   25        Delhi   288289
4      Sai   25      Chennai   288282
5     Juel   25    Hyderabad   282888
6  Santosh   25      Kolkata   228288
7      Raj   25  Bhabaneswar   227722

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_excel('mywork.xlsx', sheet_name='Sheet1')
# df.columns=["Name", "Age", "City", "Pincode"]
# print(df)
# df['Age'].mean()
# df.index 
df.set_index("Name",inplace=True)
df


Age         City  Pincode
Name                              
Tony      25     New York   826761
Thor      25     New York   281771
Gaurav    25       Mumbai   292872
Bhola     25        Delhi   288289
Sai       25      Chennai   288282
Juel      25    Hyderabad   282888
Santosh   25      Kolkata   228288
Raj       25  Bhabaneswar   227722